---
- name: Ensure Homebrew is installed (macOS)
  shell: |
    set -e
    if ! command -v brew >/dev/null 2>&1; then
      NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
  args:
    executable: /bin/bash
  when: ansible_system == 'Darwin'

- name: Tap and bundle from Brewfile if present
  shell: |
    set -e
    cd "{{ dotfiles_dir | default(ansible_env.HOME + '/.dotfiles') }}"
    if [ -f ansible/Brewfile ]; then
      brew update
      brew bundle --file ansible/Brewfile
    fi
  args:
    executable: /bin/bash
  when: ansible_system == 'Darwin'

