---
- name: Ensure zsh config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/zsh_setup"
    state: directory

- name: Stow zsh and zsh_setup packages if present
  command: "stow -t {{ ansible_env.HOME }} {{ item }}"
  args:
    chdir: "{{ dotfiles_dir | default(ansible_env.HOME + '/.dotfiles') }}"
  loop:
    - zsh
    - zsh_setup
  register: stow_result
  changed_when: true
  failed_when: false

- name: Show stow result
  debug:
    var: stow_result.stdout_lines
