set-option -g focus-events on
set -ga terminal-overrides ",xterm-256color*:Tc"
set -s escape-time 0
set -g base-index 1
set -g status-style 'bg=#333333 fg=#5eacd3'

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Splitting panes
bind -r / split-pane
bind -r \\ split-pane -h

# "Pane Resizing"
bind -r J resize-pane -D 10 # (Resizes the current pane down)
bind -r K resize-pane -U 10 # (Resizes the current pane upward)
bind -r H resize-pane -L 10 # (Resizes the current pane left)
bind -r L resize-pane -R 10 # (Resizes the current pane right)

# set-option -g status-right "Hello World"

bind-key -r f run-shell "tmux neww tmux-sessionizer"
bind-key -r i run-shell "tmux neww tmux-cht.sh"
bind-key -r p run-shell "tmux neww bpython"
bind-key -r n run-shell "tmux neww node"

bind -r T neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/documents/todo.md"
bind r source-file ~/.tmux.conf


set-window-option -g mode-keys vi
bind -r v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection

bind-key -r C run-shell "tmux-sessionizer ~/.ghq/github.com/adammomen/chance"
bind-key -r D run-shell "tmux-sessionizer ~/.dotfiles"

if-shell -b '[ "$(uname)" = "Darwin" ]' {
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy' # how to make different copy for mac and linux
}

if-shell -b '[ "$(uname)" = "Linux" ]' {
# TODO: fix this for linux
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsc' # how to make different copy for mac and linux
}

# bind-key -r H run-shell "tmux-sessionizer ~/.ghq/github.com/adammomen/chance"
