local Remap = require("adam.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<C-p>", function()
    local telescope = require('telescope.builtin')
    xpcall(
        function()
            telescope.git_files()
        end,
        function()
            telescope.find_files()
        end
    )
end)
nnoremap("<Leader>pf", function()
    require('telescope.builtin').find_files()
end)

nnoremap("<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>pb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>vsh", function()
    require('telescope.builtin').help_tags()
end)

nnoremap("<leader>vrc", function()
    require('adam.telescope').search_dotfiles({ hidden = true })
end)
nnoremap("<leader>va", function()
    require('adam.telescope').anime_selector()
end)
nnoremap("<leader>vc", function()
    require('adam.telescope').chat_selector()
end)
nnoremap("<leader>gc", function()
    require('adam.telescope').git_branches()
end)
nnoremap("<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>gm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
-- TODO: fix me here
nnoremap("<leader>td", function()
    require('adam.telescope').dev()
end)
