#!/usr/bin/env bash

alias vim="nvim"
alias vi="nvim"

alias work="cd ~/work"
alias projects="cd ~/projects"

alias python="python3"
alias pjson="python -mjson.tool"
alias cclip="pbcopy"
alias pclip="pbpaste"

alias ll='ls -al'

# Git
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias gp='git pull'
alias gpsh='git push'
alias gss='git status -s'
alias gs='echo ""; echo "*********************************************"; echo -e "   DO NOT FORGET TO PULL BEFORE COMMITTING"; echo "*********************************************"; echo ""; git status'

# Useful
alias myip="curl https://ipinfo.io/json"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"

# Tmux
alias t='tmux'
alias ta='tmux a'
alias tks='tmux kill-session -t'

# cursor
alias c='cursor'

alias du='du -sh -- */'